apiVersion: openmcp.cloud/v1alpha1
kind: ClusterProvider
metadata:
  name: "gardener"
spec:
  image: "ghcr.io/openmcp-project/images/cluster-provider-gardener:v0.1.0"
  imagePullSecrets:
    - name: "openmcp-imgpull"
